### ISSUE TITLE
add cache busting to img tags and css background images

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#127]

**Comment by adamfranco** [comment]
Given that front-end deployments are relatively infrequent (~1 per day, probably less over time), having the tag be a random thing that changes each deployment wouldn't be too problematic. Each deployment there would be a new URL that users would have to fetch and there would be an extra item in the Varnish cache for a few weeks that is no longer used -- not a big deal at all.

That said, if you can calculate the sha/md5 hash of the image and use that (or its first 8 characters) as the tag, that would be even better as this would only change if the file content itself changed -- what we are really sniffing for. Given how slow the build process is already, this extra calculation shouldn't slow it down noticeably.

A quick search for [gulp sha hash](https://www.google.com/search?q=gulp+calculate+file+sha+hash) returns a bunch of options. One is a [gulp-asset-cache](https://www.npmjs.com/package/gulp-asset-hash) plugin that purports to do pretty close to what I'm thinking about, but it changes the file-name rather than appending a query-string. Adding to just the query string means less chance of old versions files clogging things up or not being available for stale source-documents.

**Comment by zebapy** [comment]
Since the only image tags we use that do not come from Drupal are the footer logo, 404, and profile placeholder image, I'm going to hold off on this. I updated the footer logo for #124 but the filename and extension changes anyway and shouldn't be changing any time soon.. If more images get added and this becomes a problem, we can revisit. 

As for background images in css, again, the main one is the header logo. I appended a `?v2` [onto the urls](https://github.com/middlebury/frontend/commit/694ad1a800850e137751a5c035741159a37d9748#diff-2b02e399e8ff0affa293c374cc812005L49) for now and we can just update that if it changes.
