### ISSUE TITLE
Spacing issues on profile listing

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/frontend#92]
Example:

https://www.middlebury.edu/institute/academics/degree-programs/international-education-management/faculty

There was an image size issue too at one point, but it looks like maybe someone fixed that? The images would display at whatever size they were uploaded, and were not constrained.

**Comment by imcbride** [comment]
The image size issue was fixed here https://github.com/middlebury/drupal8/commit/024e1669ad4069703f09323e76fcedb423efecd7

The margin issue is also fixed in the CSS, but one of the frontend servers is not responding to its hostname right now, blocking deployment of the code. I'll close this when that's resolved.

**Comment by zebapy** [comment]
![screenshot 2018-01-25 14 13 15](https://user-images.githubusercontent.com/2199845/35407453-017b8db2-01da-11e8-8c14-e1f45a95cf92.png)

@imcbride did we need to get you any assets to get the placeholder images to work?

**Comment by imcbride** [comment]
Yes, I'll need a placeholder image, ideally at 432x576 and 144x192, unless those exist in the frontend project somewhere and I'm just missing them.

**Comment by imcbride** [comment]
The deployment issue is fixed so the problem with spacing is resolved.

Issue for placeholder images is here https://github.com/middlebury/drupal8/issues/38
